# SyncNet2
model: 
    num_segments: 20
    embed_dim: 128
    num_heads: 4
    num_layers: 2
    num_groups: 4
    actv_mode: elu
    pool_mode: mean
    k_size: [21, 11]
    hid_dim: [8, 16]
    num_classes: 3

training:
    num_epochs: 50
    num_batch: 32
    learning_rate: 1e-4
    optimizer: Adam
    exlr_on: False